version: '3.9'

services:
  server:
    image: ar2rworld/botsservice:main
    restart: always
    container_name: server
    ports:
      - 50052:50052

  client_all_over_the_news_tomorrow_bot:
    image: ar2rworld/botsservice:main
    # restart: always
    container_name: all_over_the_news_tomorrow_bot
    command: ./client
    environment:
      MESSAGESERVICE_ADDRESS: server
      MESSAGESERVICE_PORT: 50052
      NAME: olabot
    depends_on:
      - server

  client_olabot:
    image: ar2rworld/botsservice:main
    # restart: always
    container_name: olabot
    command: ./client
    environment:
      MESSAGESERVICE_ADDRESS: server
      MESSAGESERVICE_PORT: 50052
      NAME: all_over_the_news_tomorrow_bot
    depends_on:
      - server
